name: Draft Release

on:
  workflow_dispatch:

jobs:
  draft:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Development Release
        uses: robinraju/release-downloader@v1.8
        with:
          tag: nightly
          fileName: '*'
          tarBall: false
          zipBall: true
          out-file-path: 'dev'

      - name: Declare Version Variable
        id: ref
        shell: bash
        run: echo "version=$(unzip -p ${{ github.workspace }}/dev/sapphire-nightly.zip sapphire-sapphire-*/VERSION | xargs)" >> $GITHUB_OUTPUT

      - name: Move Files
        run: |
          mv dev/sapphire-installer-*-mac.pkg sapphire-installer-v${{ steps.ref.outputs.version }}-mac.pkg
          mv dev/sapphire-installer-*-win.exe sapphire-installer-v${{ steps.ref.outputs.version }}-win.exe
          mv dev/sapphire-*-mac.zip sapphire-v${{ steps.ref.outputs.version }}-mac.zip
          mv dev/sapphire-*-win.zip sapphire-v${{ steps.ref.outputs.version }}-win.zip
          mv dev/resources-win.zip resources-win.zip
          mv dev/resources-mac.zip resources-mac.zip

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.ref.outputs.version }}
          name: Sapphire v${{ steps.ref.outputs.version }}
          body: |
            TODO before publishing:
             - mark if pre-release
             - add changelog
             - remove this
          draft: true
          files: |
            ./sapphire-installer-v${{ steps.ref.outputs.version }}-mac.pkg
            ./sapphire-installer-v${{ steps.ref.outputs.version }}-win.exe
            ./sapphire-v${{ steps.ref.outputs.version }}-mac.zip
            ./sapphire-v${{ steps.ref.outputs.version }}-win.zip
            ./resources-win.zip
            ./resources-mac.zip
